# otf
slim_3500_regular_otf_run:
	pyftsubset source/AlibabaPuHuiTi-3-55-Regular.otf \
    --text-file=sc_3500.txt \
    --layout-features="*" \
    --output-file=slim/sc_3500/AlibabaPuHuiTi-3-55-Regular.otf

slim_3500_medium_otf_run:
	pyftsubset source/AlibabaPuHuiTi-3-65-Medium.otf \
    --text-file=sc_3500.txt \
    --layout-features="*" \
    --output-file=slim/sc_3500/AlibabaPuHuiTi-3-65-Medium.otf

slim_3500_bold_otf_run:
	pyftsubset source/AlibabaPuHuiTi-3-85-Bold.otf \
    --text-file=sc_3500.txt \
    --layout-features="*" \
    --output-file=slim/sc_3500/AlibabaPuHuiTi-3-85-Bold.otf

# ttf
slim_3500_regular_ttf_run:
	pyftsubset source/AlibabaPuHuiTi-3-55-Regular.ttf \
    --text-file=sc_3500.txt \
    --layout-features="*" \
    --output-file=slim/sc_3500/AlibabaPuHuiTi-3-55-Regular.ttf

slim_3500_medium_ttf_run:
	pyftsubset source/AlibabaPuHuiTi-3-65-Medium.ttf \
    --text-file=sc_3500.txt \
    --layout-features="*" \
    --output-file=slim/sc_3500/AlibabaPuHuiTi-3-65-Medium.ttf

slim_3500_bold_ttf_run:
	pyftsubset source/AlibabaPuHuiTi-3-85-Bold.ttf \
    --text-file=sc_3500.txt \
    --layout-features="*" \
    --output-file=slim/sc_3500/AlibabaPuHuiTi-3-85-Bold.ttf