name: fn_security
description: A starting point for Dart libraries or applications.
version: 0.4.0
homepage: flutter_ui
publish_to: none

environment:
  sdk: ^3.13.3

dependencies:
  crypto: ^3.0.7
  pointycastle: ^4.0.0
  fn_device:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: fn_device
  logger:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: logger

dev_dependencies:
  very_good_analysis: ^11.0.0
