name: ui_map
description: "A new Flutter project."
version: 0.0.1
homepage: flutter_ui
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  # TODO 这个库太大了，有时间把拼音内置进来
  pinyin: ^3.3.0
  alphabet_list_view: ^1.1.3
  #alphabet_list_view:
  #  git:
  #    url: https://github.com/cosee/alphabet_list_view
  #    path: /Users/huazhimeng/Desktop/flutter_ui/fork/alphabet_list_view

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  assets:
    - csv/AdminCode.csv

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
