name: ui_map
description: "A new Flutter project."
version: 0.1.2
homepage: flutter_ui
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  pinyin: ^3.3.0
  alphabet_list_view: ^1.1.4
  geolocator: ^14.0.0
  ui_webview:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_webview
  #ui_webview:
  #  path: ../ui_webview

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  assets:
    - csv/AdminCode.csv
    - html/tianditu.html

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
